<?php

// create block for map
function cclmap_block_info() {
  $blocks['cclmap'] = array(
    'info' => t('Leaflet Map for Cypress Creek Lakes'),
  );
  return $blocks;
}

// call map in the created block
function cclmap_block_view($delta = '') {
  $amenity_nodes = get_all_amenity_nodes();
  $points = cclmap_create_features($amenity_nodes);

  $blocks = array();
  $styles = cclmap_leaflet_map_info();
  $map = leaflet_render_map($styles['OSM Mapnik'], $points, '500px');
  $blocks['content'] = $map;
  return $blocks;
}

// grab all of the amenity nodes
function get_all_amenity_nodes() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'amenity')
        ->fieldCondition('field_geocoder', 'geom', 'NULL', '!=')
        //->fieldCondition('field_logo', 'fid', 'NULL', '!=')
        //->fieldCondition('field_map_pin', 'fid', 'NULL', '!=')
        //->fieldCondition('field_amenity_type', 'value', 1, '=')
        ->propertyCondition('status', 1);
  $result = $query->execute();

  if (isset($result['node'])) {
    $amenity_items_nids = array_keys($result['node']);
    $amenity_items = node_load_multiple($amenity_items_nids);
  }
  return $amenity_items;
}

// create $features array
function cclmap_create_features($nodes) {
  geophp_load();
  $amenities_arr = array();
  foreach($nodes as $node) {
    $geocoder = $node->field_geocoder;
    $point_places = geoPHP::load($geocoder['und'][0]['geom'], 'wkt');
    $longitude = $point_places->coords[0];
    $latitude = $point_places->coords[1];
    $data               = array();
    $data['type']       = 'point';
    $data['leaflet_id'] = 'amenities_' . $node->nid;
    $node_url = drupal_get_path_alias('node/' . $node->nid);

    $data['icon'] = array(
      'iconUrl' => '/' . drupal_get_path('module', 'cclmap') . '/images/commpin-master.png',
      //'iconUrl' =>  file_create_url($node->field_map_pin['und'][0]['uri']),
      'popupAnchor' => array('x' => 23, 'y' => 0),
    );

    $thuroughfare = "<div><p>" . $node->field_address['und'][0]['thoroughfare'] . "</p></div>";
    $city = "<p>" . $node->field_address['und'][0]['locality'] . ", ";
    $state = $node->field_address['und'][0]['administrative_area'] . " </p>";
    $zip = "<p>" . $node->field_address['und'][0]['postal_code'] . "</p>";

    $title = "<h4>" . $node->title . "</h4>";

    //$logo = "<img src= '" . file_create_url($node->field_logo['und'][0]['uri']) . "' />";
    $address = $thuroughfare .  $city . $state . $zip;
    $viewamenity = "<a href='/{$node_url}'> View amenity »</a>";


    $data['popup'] = $viewamenity;
    $data['lat'] = $latitude;
    $data['lon'] = $longitude;

    $amenities_arr[] = $data;
  }
  return $amenities_arr;
}

function cclmap_leaflet_map_info() {
  $settings = array(
    'attributionControl' => TRUE,
    'closePopupOnClick'  => TRUE,
    'doubleClickZoom'    => TRUE,
    'dragging'           => TRUE,
    'fadeAnimation'      => TRUE,
    'layerControl'       => FALSE,
    'maxZoom'            => 19,
    'minZoom'            =>  0,
    'scrollWheelZoom'    => FALSE,
    'touchZoom'          => TRUE,
    'trackResize'        => TRUE,
    'zoom'               => 9,
    'zoomAnimation'      => TRUE,
    'zoomControl'        => TRUE,
  );
  $map_info['OSM Mapnik'] = array(
    'label' => 'Amenities Map',
    'description' => 'A map of Cypress Creek Lakes Amenities',
    'settings' => $settings,
    'layers' => array(
      'earth' => array(
        'urlTemplate' => 'http://mt2.googleapis.com/vt?x={x}&y={y}&z={z}',
        'options' => array(
          'attribution' => 'OSM Mapnik',
        ),
      ),
    ),
  );

  return $map_info;
}
