<?php

// create block for map
function fdcmap_block_info() {
  $blocks['fdcmap'] = array(
    'info' => t('Leaflet Map for Friendswood Community Page'),
  );
  return $blocks;
}

// call map in the created block
function fdcmap_block_view($delta = '') {
  $community_nodes = get_all_community_nodes();
  $points = fdcmap_create_features($community_nodes);

  $blocks = array();
  $styles = fdcmap_leaflet_map_info();
  $map = leaflet_render_map($styles['OSM Mapnik'], $points, '500px');
  $blocks['content'] = $map;
  return $blocks;
}

// grab all of the Community nodes
function get_all_community_nodes() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'community')
        ->propertyCondition('status', 1);
  $result = $query->execute();

  if (isset($result['node'])) {
    $community_items_nids = array_keys($result['node']);
    $community_items = node_load_multiple($community_items_nids);
  }
  return $community_items;
}
