<?php

// create block for map
function fdcmap_block_info() {
  $blocks['fdcmap'] = array(
    'info' => t('Leaflet Map for Friendswood Community Page'),
  );
  return $blocks;
}

// call map in the created block
function fdcmap_block_view($delta = '') {
  $community_nodes = get_all_community_nodes();
  $points = fdcmap_create_features($community_nodes);

  $blocks = array();
  $styles = fdcmap_leaflet_map_info();
  $map = leaflet_render_map($styles['OSM Mapnik'], $points, '500px');
  $blocks['content'] = $map;
  return $blocks;
}

// grab all of the Community nodes
function get_all_community_nodes() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'community')
        ->propertyCondition('status', 1);
  $result = $query->execute();

  if (isset($result['node'])) {
    $community_items_nids = array_keys($result['node']);
    $community_items = node_load_multiple($community_items_nids);
  }
  return $community_items;
}

// create $features array
function fdcmap_create_features($nodes) {
  geophp_load();
  $communities_arr = array();
  foreach($nodes as $node) {
    $geocoder = $node->field_geocoder;
    $point_places = geoPHP::load($geocoder['und'][0]['geom'], 'wkt');
    $longitude = $point_places->coords[0];
    $latitude = $point_places->coords[1];

    $data               = array();
    $data['type']       = 'point';
    $data['leaflet_id'] = 'communities_' . $node->nid;
    $amenity_type = $node->field_type['und'][0]['value'];

    $data['icon'] = array(
      'iconUrl' => '/' . drupal_get_path('module', 'fdcmap') . '/images/amenity-miramar.png',
      'popupAnchor' => array('x' => 23, 'y' => 0),
    );

    $thuroughfare = "<div><p>" . $node->field_address['und'][0]['thoroughfare'] . "</p></div>";
    $city = "<p>" . $node->field_address['und'][0]['locality'] . ", ";
    $state = $node->field_address['und'][0]['administrative_area'] . " </p>";
    $zip = "<p>" . $node->field_address['und'][0]['postal_code'] . "</p>";

    $title = "<h4>" . $node->title . "</h4>";
    $address = $thuroughfare .  $city . $state . $zip;


    $data['popup'] = $title . $address;
    $data['lat'] = $latitude;
    $data['lon'] = $longitude;

    $communities_arr[] = $data;
  }
  return $communities_arr;
}

function fdcmap_leaflet_map_info() {
  $settings = array(
    'attributionControl' => TRUE,
    'closePopupOnClick'  => TRUE,
    'doubleClickZoom'    => TRUE,
    'dragging'           => TRUE,
    'fadeAnimation'      => TRUE,
    'layerControl'       => FALSE,
    'maxZoom'            => 19,
    'minZoom'            =>  0,
    'scrollWheelZoom'    => FALSE,
    'touchZoom'          => TRUE,
    'trackResize'        => TRUE,
    'zoom'               => 13,
    'zoomAnimation'      => TRUE,
    'zoomControl'        => TRUE,
  );
  $map_info['OSM Mapnik'] = array(
    'label' => 'Communities Map',
    'description' => 'A map of Friendswood Development Company Communities',
    'settings' => $settings,
    'layers' => array(
      'earth' => array(
        'urlTemplate' => 'http://mt2.googleapis.com/vt?x={x}&y={y}&z={z}',
        'options' => array(
          'attribution' => 'OSM Mapnik',
        ),
      ),
    ),
  );

  return $map_info;
}